"""Recreate Table

Revision ID: 0c1120eeafe6
Revises: 6a77fafe896c
Create Date: 2025-10-02 19:14:21.204056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c1120eeafe6'
down_revision: Union[str, Sequence[str], None] = '6a77fafe896c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary', sa.String(length=1024), nullable=True))
    op.add_column('jobs', sa.Column('contact', sa.String(length=1024), nullable=True))
    op.add_column('jobs', sa.Column('notes', sa.String(length=2048), nullable=True))
    op.drop_column('jobs', 'Notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Notes', mysql.VARCHAR(length=2048), nullable=True))
    op.drop_column('jobs', 'notes')
    op.drop_column('jobs', 'contact')
    op.drop_column('jobs', 'salary')
    # ### end Alembic commands ###
