"""Jobs Table

Revision ID: 10e5ce908251
Revises: 8a3d20dcdee4
Create Date: 2025-10-02 17:17:07.511455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10e5ce908251'
down_revision: Union[str, Sequence[str], None] = '8a3d20dcdee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('notes', sa.String(length=2048), nullable=True))
    op.drop_column('jobs', 'Notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Notes', mysql.VARCHAR(length=2048), nullable=True))
    op.drop_column('jobs', 'notes')
    # ### end Alembic commands ###
